import type { WallCard } from "./types";

const now = 1_718_000_000_000;

export const seedCards: WallCard[] = [
  { id: "seed-1", name: "Northside Bicycle Co.", category: "Repairs", line: "Repairs · tune ups · all bikes welcome", message: "Flat tire, noisy chain, or stubborn brakes? Drop by this week for a quick tune-up and get back on the road smoothly.", area: "Northside", city: "Brooklyn", state: "NY", country: "US", price: "$25 tune ups", phone: "+1 212 555 0142", email: "hello@northside.example", website: "https://example.com", instagram: "https://instagram.com", facebook: "https://facebook.com", theme: "biz", images: ["https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=500&q=80"], x: 4, y: 63, rotation: -3, width: 230, zIndex: 1, createdAt: now + 1 },
  { id: "seed-2", name: "Little Collins Bakery", category: "Food", line: "Artisan bread, pastries & coffee", message: "Fresh loaves hit the shelf every morning at 7. Ask for the day-old bag for affordable bread that still tastes amazing.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", email: "orders@littlecollins.example", tiktok: "https://tiktok.com", theme: "dark", images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=500&q=80"], x: 25, y: 54, rotation: 2, width: 220, zIndex: 2, createdAt: now + 2 },
  { id: "seed-3", name: "Green Thumb", category: "Home", line: "Plant sitting · watering · repotting", message: "Going away for the weekend? Your plants get scheduled care, photo updates, and repot support when needed.", area: "Greenpoint", city: "Brooklyn", state: "NY", country: "US", price: "$25 / visit", theme: "cream", images: ["https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=500&q=80"], x: 47, y: 54, rotation: 4, width: 218, zIndex: 3, createdAt: now + 3 },
  { id: "seed-4", name: "Paws & Parks", category: "Pets", line: "Dog walking & pet sitting", message: "Friendly neighborhood walks with route tracking and photo check-ins. Senior dogs and shy pets are welcome.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", price: "$20 / 30 min", theme: "pink", images: ["https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=500&q=80"], x: 68, y: 72, rotation: -1, width: 210, zIndex: 4, createdAt: now + 4 },
  { id: "seed-5", name: "Spin City", category: "Shops", line: "Vinyl records · buy · sell · trade", message: "Bring your crate for same-day trade credit. New arrivals drop every Friday with listening station previews.", area: "Bedford-Stuyvesant", city: "Brooklyn", state: "NY", country: "US", theme: "ticket", images: ["https://images.unsplash.com/photo-1461360228754-6e81c478b882?auto=format&fit=crop&w=500&q=80"], x: 6, y: 342, rotation: -7, width: 220, zIndex: 5, createdAt: now + 5 },
  { id: "seed-6", name: "Blue Clay", category: "Classes", line: "Handmade pottery & workshops", message: "Try a beginner wheel class this weekend. All materials included and you keep one finished piece.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", theme: "cyan", images: ["https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=500&q=80"], x: 29, y: 324, rotation: 3, width: 220, zIndex: 6, createdAt: now + 6 },
  { id: "seed-7", name: "Neat Fit Tailoring", category: "Services", line: "Hem · alter · repair · custom fitting", message: "Suit too loose or jeans too long? Precision alterations with quick turnaround and fitting by appointment.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", theme: "paper", images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=500&q=80"], x: 51, y: 351, rotation: -2, width: 222, zIndex: 7, createdAt: now + 7 },
  { id: "seed-8", name: "Brush & Roll", category: "Home", line: "Interior · exterior · free estimates", message: "Color consult plus clean edge work for apartments and storefronts. Free estimate within 24 hours.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", theme: "cream", images: ["https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?auto=format&fit=crop&w=500&q=80"], x: 73, y: 342, rotation: 4, width: 218, zIndex: 8, createdAt: now + 8 },
  { id: "seed-9", name: "Math Tutor", category: "Classes", line: "Grades 6–12 · homework · test prep", message: "Clear, patient tutoring for algebra through pre-calc. Weekly progress updates for parents included.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", price: "$40 / hr", theme: "yellow", images: [], x: 8, y: 648, rotation: -4, width: 195, zIndex: 9, createdAt: now + 9 },
  { id: "seed-10", name: "Lofty Cleaning", category: "Services", line: "Apartments · offices · move in/out", message: "Reliable cleaning team for recurring or one-time deep cleans. Bring-your-own-products option available.", area: "Brooklyn", city: "Brooklyn", state: "NY", country: "US", theme: "paper", images: ["https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=500&q=80"], x: 31, y: 630, rotation: 1, width: 210, zIndex: 10, createdAt: now + 10 },
  { id: "seed-11", name: "Taco Loco", category: "Food", line: "Mexican street food · catering · events", message: "From office lunches to weekend parties, tacos are made fresh and packed hot. Vegetarian trays available.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", theme: "pink", images: ["https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=500&q=80"], x: 53, y: 621, rotation: -2, width: 225, zIndex: 11, createdAt: now + 11 },
  { id: "seed-12", name: "Piano Lessons", category: "Classes", line: "Beginners welcome · all ages", message: "Learn fundamentals, rhythm, and confidence one song at a time. In-home and studio sessions available.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", price: "$35 / 30 min", theme: "paper", images: ["https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=500&q=80"], x: 76, y: 639, rotation: 3, width: 215, zIndex: 12, createdAt: now + 12 },
  { id: "seed-13", name: "BK Photo Co.", category: "Services", line: "Portraits · events · film", message: "Natural-light portraits and documentary-style event coverage. Digital gallery delivered within 72 hours.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", theme: "photo", images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=500&q=80"], x: 16, y: 891, rotation: 1, width: 205, zIndex: 13, createdAt: now + 13 },
  { id: "seed-14", name: "Rooftop Yoga", category: "Classes", line: "Vinyasa · all levels · Sundays 10am", message: "Start your Sunday with open-sky flow and a friendly group. Bring a mat and water, we provide blocks.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", price: "$15 drop in", theme: "kraft", images: ["https://images.unsplash.com/photo-1545389336-cf090694435e?auto=format&fit=crop&w=500&q=80"], x: 39, y: 891, rotation: -1, width: 220, zIndex: 14, createdAt: now + 14 },
  { id: "seed-15", name: "Electric Ally", category: "Services", line: "Repairs · lighting · outlets · upgrades", message: "Licensed electrical help for fast fixes and safe upgrades. Evening appointments available for busy schedules.", area: "Brooklyn", city: "Brooklyn", state: "NY", country: "US", theme: "blueprint", images: ["https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=500&q=80"], x: 63, y: 900, rotation: 2, width: 215, zIndex: 15, createdAt: now + 15 },
  { id: "seed-16", name: "Handy Jay", category: "Home", line: "Shelves · furniture · fixtures · more", message: "From flat-pack assembly to wall mounting, small jobs are welcome. Clean finish and punctual service.", area: "Williamsburg", city: "Brooklyn", state: "NY", country: "US", price: "$50 / hr", theme: "yellow", images: [], x: 83, y: 891, rotation: -3, width: 195, zIndex: 16, createdAt: now + 16 },
  { id: "seed-17", name: "Venice Boardwalk", category: "Shops", line: "Streetwear · vintage · vinyl", message: "Limited drops, curated vintage, and hard-to-find records all in one stop near the boardwalk.", area: "Venice", city: "Los Angeles", state: "CA", country: "US", theme: "dark", images: ["https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=500&q=80"], x: 24, y: 130, rotation: 3, width: 220, zIndex: 17, createdAt: now + 17 },
  { id: "seed-18", name: "Sunset Cleaners", category: "Services", line: "Same-day dry cleaning & tailoring", message: "Rush cleaning before events with optional same-day pickup. Alterations available for formalwear and uniforms.", area: "Sunset", city: "Los Angeles", state: "CA", country: "US", theme: "paper", images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=500&q=80"], x: 50, y: 146, rotation: -2, width: 215, zIndex: 18, createdAt: now + 18 },
  { id: "seed-19", name: "Studio 9 Fitness", category: "Classes", line: "Pilates · HIIT · mornings & evenings", message: "Small-group classes with coaches who adapt every workout to your level. First drop-in includes assessment.", area: "Silver Lake", city: "Los Angeles", state: "CA", country: "US", price: "$18 drop in", theme: "cyan", images: ["https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=500&q=80"], x: 68, y: 134, rotation: 1, width: 220, zIndex: 19, createdAt: now + 19 },
  { id: "seed-20", name: "West Coast Espresso", category: "Food", line: "Coffee, pastries & wifi", message: "Neighborhood cafe with fast wifi, quiet tables, and rotating pastry specials baked daily.", area: "Downtown", city: "Los Angeles", state: "CA", country: "US", theme: "pink", images: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=500&q=80"], x: 82, y: 152, rotation: -4, width: 210, zIndex: 20, createdAt: now + 20 },
];
